### ISSUE TITLE
evil-collection should not change the configuration of other packages

### ISSUE THREAD

**Issue by bling** [jojojames/evil-collection#72] opened 2018-01-10 01:53 UTC
My company config "broke" after I pulled in evil-collection because the enter key wasn't bound to anything anymore.  After some digging, it appears that evil-collection's company integration turns on `company-tng` by default (which is not upstream), which in turn unbinds `return`.

Thankfully there's already a flag, but IMO, this should be off by default since it changes the behavior of the package.

Perhaps it'd be better to check `company-backends` and enable/disable as necessary and add a recommendation in the README to run `evil-collection-init` in `after-init` so you can reliably check these variables and only apply evil bindings when the user has turned on a particular feature.

**Comment by dieggsy** [comment] 2018-01-10 02:13
I sort of agree with you. I had made a similar point in #51, but backed off from the "off by default" opinion since I was happy enough with the flag existing at all. I think it's a pretty good point that it shouldn't "break" what's already there.

The point was made, however, that evil-collection should also suit the needs of someone looking for a "vim-like" experience out of the box, without putting so much effort on them. I guess the caveat is that people _not_ looking for a vim-like experience and that don't know about the flag get unexpected behavior out of the box. I kinda the idea of checking what the user has enbled, but that kind of breaks the "out of the box vim-like experience" @jojojames said he was shooting for anyway. In any case, this probably deserves some more consideration.

A side note: When `evil-collection-init` is run doesn't matter as much, it defaults to loading bindings in a `with-eval-after-load` for whatever feature is being enhanced.

**Comment by dieggsy** [comment] 2018-01-10 02:50
> I'm curious how long it took you to figure out it was evil-collection 'breaking' your configuration and how long you'd expect a relatively new vim->emacs user to figure out how to get their completion to mirror vim's ycmd.
>
>I think that better informs this particular issue (which default to move towards).

I agree

> For this particular issue (company-tng), I don't have a strong opinion on it, but I do think it being on by default is more in line with the user experience goal.

I think I personally don't need any changes, I was sorta pointing out that more discussion could help settle the matter for anyone who either really wants this or really doesn't. 

> e.g. We give you a set of defaults, remove what you don't like. ... I'd prefer the former, the latter isn't a good experience in my opinion.

Perhaps you're right - in a sense, isn't this what _all_ of evil-collection is doing? All of these bindings are in a way "a set of defaults" that the user can change if they don't like. In the end a lot of these settings end up being a matter of personal preference, and the default isn't as important as the ability to change it.

> Would adding a set of configuration variables in the README that may be of interest (including this company change) be a good middleground @bling @dieggsy?

More documentation never hurt anyone :)

**Comment by bling** [comment] 2018-01-10 03:41
>I'm curious how long it took you to figure out it was evil-collection 'breaking' your configuration and how long you'd expect a relatively new vim->emacs user to figure out how to get their completion to mirror vim's ycmd.

longer than it should have.... i initially thought a new version of company had a breaking change, so i scanned the release notes, but didn't see any changes that would affect it.  i eventually looked at `company-active-map` itself and discovered that `RET` was bound to `nil`, and then did a brute-force search of my entire `elpa` to see what was changing it -- not fun.

also, by mimicking the behavior of YCM you are implicitly saying that "vim-like" means using that instead of deoplete.vim, autocomplpop, supertab, or any one of the other completion plugins.

and lastly, (while it's not "vim-like") most other modern editors like vscode/atom will complete the current match upon hitting `RET`.  the newbie might actually be surprised why they are inserting a new line and try to fix that instead.

> I'm not sure what you mean by this. company-tng is part of company mode.

yes, but it's off by default.  unless you're actively following company-mode development, everyone who pulls down evil-collection is in for a surprise.

> e.g. We give you a set of defaults, remove what you don't like.
> vs -> We don't set any defaults, add what you want. (What you expect in Emacs usually).
> I'd prefer the former, the latter isn't a good experience in my opinion.

to me it seems odd to optimize for the "new vim -> emacs" user because then you'd be directly competing against spacemacs.  also, i'd say the majority of your current user base and for the foreseeable future are existing non-spacemacs users, not newbies.

> Would adding a set of configuration variables in the README that may be of interest (including this company change) be a good middleground @bling @dieggsy?

now that is very emacs-like 😄

**Comment by jojojames** [comment] 2018-01-10 04:02
> longer than it should have.... i initially thought a new version of company had a breaking change, so i scanned the release notes, but didn't see any changes that would affect it. i eventually looked at company-active-map itself and discovered that RET was bound to nil, and then did a brute-force search of my entire elpa to see what was changing it -- not fun.

Welp. :)

> also, by mimicking the behavior of YCM you are implicitly saying that "vim-like" means using that instead of deoplete.vim, autocomplpop, supertab, or any one of the other completion plugins.

Yup, I am ok with that implicit statement. Most of those mentioned plugins don't get much use IIRC (even when I was using vim). Deoplete maybe..
I digress.. I've really only seen YCMD requested in Emacs.

> yes, but it's off by default. unless you're actively following company-mode development, everyone who pulls down evil-collection is in for a surprise.

There's the counter to that which is many who pull down company don't have to configure it by hand since it's set up how they'd want it anyways. (I have seen first hand this happen.)

> to me it seems odd to optimize for the "new vim -> emacs" user because then you'd be directly competing against spacemacs.
> also, i'd say the majority of your current user base and for the foreseeable future are existing non-spacemacs users, not newbies.

I think it's more fair to say I keep the new user's experience in mind *more* than most emacs developers. :)

I don't think the mindset "We give you a set of defaults, remove what you don't like." is necessarily a newbie-focused mindset either, just different. :)

@dieggsy put it better than me.

> Perhaps you're right - in a sense, isn't this what all of evil-collection is doing? All of these bindings are in a way "a set of defaults" that the user can change if they don't like. In the end a lot of these settings end up being a matter of personal preference, and the default isn't as important as the ability to change it.

I'm not sure why this particular configuration is any different. We could be talking about a completely different default/binding which could have led you down the same rabbit hole.

Again, I don't have strong feelings for this *particular* change, but I'm not convinced it's principably different from the slew of other setup functions that are being called in evil-collection.

> now that is very emacs-like 😄

If this will help ease any confusion, I'll add it as soon as I can. :)

**Comment by bling** [comment] 2018-01-10 05:28
> I'm not sure why this particular configuration is any different. We could be talking about a completely different default/binding which could have led you down the same rabbit hole.

i think it boils down to the principle of least surprise.  both @dieggsy and i were surprised enough to open a PR and a ticket respectively.

> Again, I don't have strong feelings for this particular change, but I'm not convinced it's principably different from the slew of other setup functions that are being called in evil-collection.

this is unique because we are discussing something that affects **insert** mode, and a completion plugin at that, where key bindings and configuration are one and the same.

the only other package that would run into the same thing is `auto-complete`, of which i must ask, would you also configure it to have the same `TAB/RET` behavior?  what if i have `yasnippet` installed?  are you going to change how `TAB` works so it detects whether i want to expand a snippet or not?  the slope gets slippery very fast.

ultimately the decision is up to you, as long as there's an escape hatch, but it would be very helpful to define in your README exactly what you mean to be "vim-like", which currently appears to involve configuring emacs packages to emulate popular equivalent vim plugins.

**Comment by jojojames** [comment] 2018-01-10 08:42
> i think it boils down to the principle of least surprise. both @dieggsy and i were surprised enough to open a PR and a ticket respectively.

You won't see an accurate ratio of people happy/unhappy because people that don't have a problem with it won't post an issue (or won't bother to).

It could very well be that 9/10 are happy with the defaults won't bother posting anything. Either way, there's an escape latch through disabling the integration or setting the defcustom to false.

> this is unique because we are discussing something that affects insert mode, and a completion plugin at that, where key bindings and configuration are one and the same.

There's no distinction between the evil states, for me.

AutoCompletion as a feature is similarly un-unique with regards to "here's a sane set of defaults, disable it if you don't like it" mentality.

> the only other package that would run into the same thing is auto-complete, of which i must ask, would you also configure it to have the same TAB/RET behavior?

If auto-complete had the capability to add ycmd-like behavior, I'd be open to it.

> but it would be very helpful to define in your README exactly what you mean to be "vim-like", which currently appears to involve configuring emacs packages to emulate popular equivalent vim plugins.

Do you have the same problem with evil-collection implicitly supporting unimpaired (#64)? To me, it follows along those same lines.

Lastly,

> to me it seems odd to optimize for the "new vim -> emacs" user because then you'd be directly competing against spacemacs.

Please don't discount users that just want no-hassle emacs+evil. Spacemacs is fantastic but its abstractions might be too heavy for people that just want a simple setup.
emacs+evil+(evil-collection) is a really solid starting point for just that type of person.

**Comment by jojojames** [comment] 2018-01-10 08:53
I think defaults are always going to be a tricky topic but it's best to have the beginner in mind when choosing them.  

I'll look into updating the README as a nice middleground.

Going to close this topic, please reopen if you have new points to add. :)

If I get more complaints on this topic, I'll reconsider and then get ready for the reverse issue.

https://xkcd.com/1172/

**Closed by jojojames** 2018-01-10 08:53 UTC

**Comment by bling** [comment] 2018-01-10 13:43
> Do you have the same problem with evil-collection implicitly supporting unimpaired (#64)? To me, it follows along those same lines.

i don't mind because it's not a primary feature -- most people probably don't even use that key binding despite it being installed in every vim distribution.  also, i know of no other plugin which uses those bindings, giving it defacto ownership of those keys.  on the other hand, completion is something the vast majority of users will use, everyone has it configured differently, which should change how it gets treated.

however, if it ever became contentious for unimpaired my automatic response would be to remove both sides and bind nothing.  it is easier to add bindings than it is to remove them.  vim-sensible went through countless iterations of adding/remove default settings, and i think it had some of the same challenges as evil-collection, in that both wanted to have sensible defaults for new users.  the problem is that these projects came late in the game and users already had *years* of configuring things and you're going to have objections for everything.

**Comment by jojojames** [comment] 2018-01-10 17:55
> i don't mind because it's not a primary feature

My point was around the 'implicit' support of a vim plugin other than base vim.

> however, if it ever became contentious for unimpaired my automatic response would be to remove both sides and bind nothing.

I think we disagree here. I'd prefer picking a sensible (for whatever metric we can use for sensible) default and making it possible for the alternative. If you want to disable features everytime there's a potential clash, the way is to start evil-collection would be to empty the mode list empty and add what you like (like spacemacs layers).

Principally, we're going the opposite direction, give them everything, let them remove/change what they don't want.

**Comment by jojojames** [comment] 2018-01-11 02:22
Added configuration section to readme.
